export enum FilterTypesEnum {
    None = 0,
    Optic_Side,
    Tire_Diameter,
    Tire_FrameSize,
    Tire_Season,
    Tire_Usage,
    Tire_Width,
    Tire_AxisType,
    Oil_Purpose,
    Oil_Viscosity,
    Oil_Scope,
    Oil_Applicability,
    Oil_Type,
    Oil_SpecAPI,
    Oil_SpecACEA,
    Oil_SpecLSAC,
    Oil_SpecJASO,
    Oil_SpecOEM,
    Oil_ISO,
    Accum_CaseType,
    Accum_Capacity,
    Accum_Polarity,
    Accum_Voltage,
    Accum_Start,
    Accum_Length,
    Accum_Width,
    Accum_Height,
    Accum_Terminal,
    Lamp_Power,
    Lamp_Base,
    Lamp_Voltage,
    Lamp_Xenon,
    TechnicalFluids_Purpose,
    TechnicalFluids_Color,
    TechnicalFluids_Seasonality,
    TechnicalFluids_SpecOEM,
    TechnicalFluids_Scope,
    //Disks
    WheelDisc_Width, 
    WheelDisc_Diameter, 
    WheelDisc_PCD, 
    WheelDisc_ET, 
    WheelDisc_DIA, 
    WheelDisc_Color, 
    //Manufacturers section
    Uncategorized_Manufacturer = 1000,
    Optic_Manufacturer = 1001,
    Tire_Manufacturer = 1002,
    Oil_Manufacturer = 1003,
    Accum_Manufacturer = 1004,
    Lamp_Manufacturer = 1005,
    TechnicalFluids_Manufacturer = 1006,
    WheelDisc_Manufacturer = 1007,
    //Suitable vehicles section
    SuitableVehicles_Mark = 2000,
    SuitableVehicles_Serie = 2001,
    SuitableVehicles_Year = 2002,
    SuitableVehicles_Model = 2003,
    SuitableVehicles_Modif = 2004
}