export { AddReviewComponent } from "./add-review.component";
export { BrandReviewsComponent } from "./brand-reviews.component";
export { ProductRateComponent } from "./product-rate.component";
export { ProductRateSmallComponent } from "./product-rate-small.component";
export { ProductReviewsComponent } from "./product-reviews.components";
export { ReviewComponent } from "./review.component";
export { BrandReviewComponent } from "./brand-review.component";
export { ReviewsListComponent } from "./reviews-list.component";
export { StarComponent } from "./star.component";