export enum LogEntryType {
    Unknown = 0,
    Exception = 1,
    //InvalidAccess,
    //Login,
    //RestorePassword,
    //InvoiceOperation,
    //Search,
    //ProductCard = 7,
    //ManagerMail,
    //SearchPrice,
    //SearchRest,
    //GetImage,
    //FileUpload,
    ShoppingCart = 13,
    ShopingCartPageEnter = 35,
    ProductPriceChanged = 36,
    ProductOutOfStock = 37,
    FindDetailPageEnter = 38,
}